# site settings
title: Tyler Chase
subtitle:
email:
description: A college student who has too much stuff he wants to learn, and not enough hours in a day to do so.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
github_url: https://github.com/tylercchase
linkedin_url: https://www.linkedin.com/in/tylercchase/
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed

